name: "Github Sync Projects"
description: "Github Sync Projects"
author: "Fabiano Chiaretto Fernandes"
branding:
  icon: "edit"
  color: "purple"
runs:
  using: "node16"
  main: "dist/index.js"
inputs:
  github-token:
    description: "The GITHUB_TOKEN secret"
    required: true
  debug:
    description: "Debug GraphQL"
    required: false